# select ins.animal_id, ins.name
# from animal_ins ins
# left outer join animal_outs outs
# on ins.animal_id = outs.animal_id
# where ins.datetime > outs.datetime
# order by ins.datetime

# # -- 코드를 입력하세요
# SELECT INS.ANIMAL_ID, INS.NAME
# FROM ANIMAL_INS AS INS
# LEFT JOIN ANIMAL_OUTS AS OUTS
# ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
# WHERE INS.DATETIME > OUTS.DATETIME
# ORDER BY INS.DATETIME


# SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME 
# FROM ANIMAL_INS 
# LEFT JOIN ANIMAL_OUTS 
# ON ANIMAL_INS.ANIMAL_ID=ANIMAL_OUTS.ANIMAL_ID 
# WHERE ANIMAL_INS.DATETIME>ANIMAL_OUTS.DATETIME 
# ORDER BY ANIMAL_INS.DATETIME

SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_INS I
INNER JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.DATETIME > O.DATETIME
ORDER BY I.DATETIME ASC;