# -- 코드를 입력하세요
# SELECT HALF.FLAVOR
# FROM FIRST_HALF AS HALF, ICECREAM_INFO AS INFO
# WHERE HALF.FLAVOR = INFO.FLAVOR AND HALF.TOTAL_ORDER > 3000 AND INFO.INGREDIENT_TYPE = 'fruit_based'
# ORDER BY HALF.TOTAL_ORDER DESC

SELECT INFO.FLAVOR
FROM FIRST_HALF HALF, ICECREAM_INFO INFO
WHERE HALF.FLAVOR = INFO.FLAVOR AND HALF.TOTAL_ORDER > 3000 AND INFO.INGREDIENT_TYPE = 'fruit_based'
ORDER BY HALF.TOTAL_ORDER DESC